language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_KEY"
  app: app-udemy-devops
  edge: true
deply:
  api_key:
    secure: coQM5KJTsn4Ct8Fj4x3CPkw2gLou38RE9qSJwiVIx4303sDamznFnA90xg3Vugt2IddnvHclHwGyZBiG6Ainx31AMTYCjPuAXzfBAHIJC9pNcdpREejxGs8Q/JZUafk/7G1r25AkTq4Icx1RdRNhCsfEG1LU2/GxQGBkHNKJmEvhDfX0lfwY5unYyGQ2un9swwoUhKmx5jJTN8U32dTM4mSLjrU+BVxwZTvHRtCYQqq90jEeWV8H7vWnKRd3kEzDt6zplNhOyMT64cyePoOwYeE2zQD1J+zJuTVe1kJYTMFoBzM9y/dyygS7Ki0O9RJpfXvIIGqblzin3q4/JrytVCBfBTPXgSMbTlau3zRLhKErQiqqLlM8a3o72zIiIwh1V5GR6a45i0o3+F3ikDWdDBv+w84CYzktHomUKKWu1v4tsu2jvSITjtA/NTcNcViZyqd0RkMgLMwCBkoJSo9HWSjna7veL8+x8f1hlYg/wzs+pd0eHUvYB4Zsirn1jrW+BtDYeIQHqGYJ0IXJbetupfL1lsmWYyuohL2pc3T0onhihQNJEOG2+PLv6+6Sy66YTDvHt/N6ivQlGZpzKWzXcTk6kDSwmpNJWOooKZIowDYaXnrUgtD4f24bG4BnNUTnwf6bVN0PsMu+CUhmVuAGVIVwegKSgbBTJolEDMegFB0=
