language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: k3srNy+kZhOqVgy1j1lawIe2QaKBVmHSetUayKrUmh0DNmjaz6ggo3UwmHpJThuegXoFiXctDRdcHqDaS0K3HDPdjo9OMII4ZgtX17L78SNBopt7A4vYgfJC3Z5BJtOdM9yY2nBoW0b31jiJeqbGOgWNDLUkl3hIv6V7nn256+EtGV2SvJeQv8h94jVFJZFVYU0xcA2RS6d6vfiFtz4L6z2TPMyx6t+Kg9wgRzcNV8uitVUuqYLiLphWBO4QikDvyBA4/5jURDTLzNnOpo5kwS+qPWw7vy0g2/6iEx8D1rtJPRCJvwAKLyHidW52fhA3A9iwF5zCaGF1W8Ex6cl8GjOlDqE2kEB7+go4a9i8BAlQsy9Zz/nNiaVq5qUDP1d4tkLKyZYhUiJZaEMKwnKLXjGUFHN5t2NLJUvL61OCJknTT/N4ZnqOjZpjF92gniquBvjz5uxZZ5TZr2Ts/XPqHe45jwiHDJgODzDrft9nILz5KbDsOziC5/+dgdeKx+jr9WWohnOqDHpS93ChMvTcx7+Vzva8wEhg/55fRoEVDMun/56r01ojnV/dc2gCkdoMWZpuj5VdRh+I4jtkuQEfZE7uM3T2oL2MzlfZ6FOgURjhPlGZQE75nEllrVS8NM2dRlT8SaVte44O0faL/CbEzYVfGcJ1uqWAMAJ0L9lfDcQ=
  app: app-udemy-devops
  edge: true
