language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: Ckuwzam4TBSiSN1uLAKqNGHrHTi4Uikm4vpi84Yefrhq7t7es3DH51rVJFZgxYteAiwhGP+Wm5/Jh5XL0AuEFV7e0X4n+mrFzK0zDZf5ncZD0/GSI6Ve8LBhvVnt3puxKQEVvMI30RIGEtH3kLkik4uGKXF+teedWbOyH7O1qgFK+Bhgj4kQC050oxQ7m3C93nDzlrmn794WH3rbLEFMbuoBqPiDDnFdh76xnTaP3w9hDGrSV2EWZ2NAg2iiXLWtS7KLekv3DrvdxsBQZ5VSUI/lf6WDcxBnNbGSNT8yIhWyY9q7pZx1oGnDLeZxU1Nj0iXX2JkLPLzSnt6qEMyMwrvVIW6pORVGboj5dcdEalrKVnW7cRgiZJ4OtZnDJ7Y0nGdTTi7xfTq7Nau6RH3JiEtvb7QVVB4vd0C0HXOXu3FRhpvJeJBFVvARFKCGRtzCrh4PAdOu8g/g1qi3FinMpcuq98vmBWAW+qGPIkRaO3j7cDsiSZ7x6AZAjst9IhbUNsXrsYc4a3vJz4O8jhIJxd9womJVReJ6Ek81EGLLwrPLs4dLUqehzkCXTtWkDZY2JpjhtMAs/Qrgo6WrKyanv73Uhb5Fu8b8pWiknRqM1ZARVUHWch7R2vo1Xik1m/CWINev5E3R0MHZwcC/dYyI0P4mDwTLOLLPJQ6a7ihsGls=
  app: app-udemy-devops
  edge: true
