language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: ad6sJpgTfzvtgmlMA3qPn+hOHLSXgns8CuF4eb5wKewYGHE4wPWuLsbDfwTJDspsnzUWh00BPFVZoWOYjp5ygwV2IB5vKFPdUWKwXzRfUnFY3sX1IWzFoN0HgTBRZjoAz/WVBYWY5PGshW2kWX9fPQolIv6RKmGMCyoQzIYvVbJQfG7MDbLsQ6ezp/hTfQxe9rWva0r1XMmAZqmI6h7wlVVs3TIaRhxBLrnqBtpa9kKeaYopb5T8LeCo5vetGAUX4WPHq4HMJU/RWMCdBWy+wDrb08VRKcu6DS3myKiQQGC/BxibzFwhKDKEoGXZurmOuBtbgLJ+QOie45tGUSVzooDs4C0xzhOVgHxoRRZc1lujeoYd+tk7OrpKNuBGTmWYZBegoPWbB9/h4Wh+vdIQ1NSKrwGlrbkmIqLFFABJu21OCm0IlVRhXetW7ircqzwQblffLCGBDKtjQXpz7VPRceET5QW21BB0SgXXPJmOx6spfKhn9jzl22hOtO+vUKlifxGxEYi9YY1LsPPpgCayfRHslqcwoWHSIsOD1+hJ8tqCtXPkOiVnohr5WE/09gGqhybmWCzgA9hHRCw80kA2+1PkBPppCBATWMFYxBCDHyyhSEApPW0QbgWsTFP4xl11k3J30XwmdrAOpsf2bIGGHWhgcVVRJjFZEoD367/V26o=
  app: app-udemy-devops
  edge: true
